#!/usr/bin/perl

# To permit this cgi, replace # on the first line above with the
# appropriate #!/path/to/perl shebang, and on Unix / Linux also
# set this script executable with chmod 755.
#
# ***** !!! WARNING !!! *****
# This script echoes the server environment variables and therefore
# leaks information - so NEVER use it in a live server environment!
# It is provided only for testing purpose.
# Also note that it is subject to cross site scripting attacks on
# MS IE and any other browser which fails to honor RFC2616. 

##
##  printenv -- demo CGI program which just prints its environment
##
use strict;
use warnings;
use CGI qw(:standard);
use Cwd;
use File::Basename;
use JSON;
print header();
chdir("Kunal_NBA");
foreach my $var (sort(keys(%ENV))) {
    my $val = $ENV{$var};
    $val =~ s|\n|\\n|g;
    $val =~ s|"|\\"|g;
    print "${var}=\"${val}\"\n";
}
local $/;
open( my $fh, '<', 'players.js' );
my $json_text   = <$fh>;
my $perl_scalar = decode_json( $json_text );
foreach my $item( @$perl_scalar ) {
my $id = $item->{'playerId'};
my $outJSONfl = "output/$id.js";
my @sysargs = (
	"'/usr/bin/curl' 'http://stats.nba.com/stats/playerprofile/?LeagueID=00&PlayerID=$id&Season=2015-16&SeasonType=Regular%20Season&GraphStartSeason=2015-16&GraphStat=PTS&GraphEndSeason=2015-16' >> '$outJSONfl'"
	);
print(@sysargs);
system(@sysargs);

    # fields are in $item->{Year}, $item->{Quarter}, etc.
}
